// Generated by gencpp from file direction_publisher/direction_msg.msg
// DO NOT EDIT!


#ifndef DIRECTION_PUBLISHER_MESSAGE_DIRECTION_MSG_H
#define DIRECTION_PUBLISHER_MESSAGE_DIRECTION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace direction_publisher
{
template <class ContainerAllocator>
struct direction_msg_
{
  typedef direction_msg_<ContainerAllocator> Type;

  direction_msg_()
    : state(0)
    , rusult(0)  {
    }
  direction_msg_(const ContainerAllocator& _alloc)
    : state(0)
    , rusult(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _rusult_type;
  _rusult_type rusult;





  typedef boost::shared_ptr< ::direction_publisher::direction_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::direction_publisher::direction_msg_<ContainerAllocator> const> ConstPtr;

}; // struct direction_msg_

typedef ::direction_publisher::direction_msg_<std::allocator<void> > direction_msg;

typedef boost::shared_ptr< ::direction_publisher::direction_msg > direction_msgPtr;
typedef boost::shared_ptr< ::direction_publisher::direction_msg const> direction_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::direction_publisher::direction_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::direction_publisher::direction_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::direction_publisher::direction_msg_<ContainerAllocator1> & lhs, const ::direction_publisher::direction_msg_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.rusult == rhs.rusult;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::direction_publisher::direction_msg_<ContainerAllocator1> & lhs, const ::direction_publisher::direction_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace direction_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::direction_publisher::direction_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::direction_publisher::direction_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::direction_publisher::direction_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::direction_publisher::direction_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::direction_publisher::direction_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::direction_publisher::direction_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::direction_publisher::direction_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5be09278843569de4bf740957660e27";
  }

  static const char* value(const ::direction_publisher::direction_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5be09278843569dULL;
  static const uint64_t static_value2 = 0xe4bf740957660e27ULL;
};

template<class ContainerAllocator>
struct DataType< ::direction_publisher::direction_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "direction_publisher/direction_msg";
  }

  static const char* value(const ::direction_publisher::direction_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::direction_publisher::direction_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state\n"
"uint8 rusult\n"
;
  }

  static const char* value(const ::direction_publisher::direction_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::direction_publisher::direction_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.rusult);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct direction_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::direction_publisher::direction_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::direction_publisher::direction_msg_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "rusult: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rusult);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIRECTION_PUBLISHER_MESSAGE_DIRECTION_MSG_H
