// Generated by gencpp from file server_client/RandomResponse.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_MESSAGE_RANDOMRESPONSE_H
#define SERVER_CLIENT_MESSAGE_RANDOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_client
{
template <class ContainerAllocator>
struct RandomResponse_
{
  typedef RandomResponse_<ContainerAllocator> Type;

  RandomResponse_()
    : result()
    , answer(false)  {
    }
  RandomResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , answer(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;

   typedef uint8_t _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::server_client::RandomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_client::RandomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RandomResponse_

typedef ::server_client::RandomResponse_<std::allocator<void> > RandomResponse;

typedef boost::shared_ptr< ::server_client::RandomResponse > RandomResponsePtr;
typedef boost::shared_ptr< ::server_client::RandomResponse const> RandomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_client::RandomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_client::RandomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_client::RandomResponse_<ContainerAllocator1> & lhs, const ::server_client::RandomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_client::RandomResponse_<ContainerAllocator1> & lhs, const ::server_client::RandomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::server_client::RandomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_client::RandomResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_client::RandomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_client::RandomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_client::RandomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_client::RandomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_client::RandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5ce192a3dda5c1561fd1d9758b911e8";
  }

  static const char* value(const ::server_client::RandomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5ce192a3dda5c15ULL;
  static const uint64_t static_value2 = 0x61fd1d9758b911e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::server_client::RandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_client/RandomResponse";
  }

  static const char* value(const ::server_client::RandomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_client::RandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"bool answer\n"
"\n"
;
  }

  static const char* value(const ::server_client::RandomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_client::RandomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RandomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_client::RandomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_client::RandomResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
    s << indent << "answer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_CLIENT_MESSAGE_RANDOMRESPONSE_H
