// Generated by gencpp from file server_client/Random.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_MESSAGE_RANDOM_H
#define SERVER_CLIENT_MESSAGE_RANDOM_H

#include <ros/service_traits.h>


#include <server_client/RandomRequest.h>
#include <server_client/RandomResponse.h>


namespace server_client
{

struct Random
{

typedef RandomRequest Request;
typedef RandomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Random
} // namespace server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_client::Random > {
  static const char* value()
  {
    return "9ce749d1ee926b7f0c91f1f5eca73de3";
  }

  static const char* value(const ::server_client::Random&) { return value(); }
};

template<>
struct DataType< ::server_client::Random > {
  static const char* value()
  {
    return "server_client/Random";
  }

  static const char* value(const ::server_client::Random&) { return value(); }
};


// service_traits::MD5Sum< ::server_client::RandomRequest> should match
// service_traits::MD5Sum< ::server_client::Random >
template<>
struct MD5Sum< ::server_client::RandomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_client::Random >::value();
  }
  static const char* value(const ::server_client::RandomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client::RandomRequest> should match
// service_traits::DataType< ::server_client::Random >
template<>
struct DataType< ::server_client::RandomRequest>
{
  static const char* value()
  {
    return DataType< ::server_client::Random >::value();
  }
  static const char* value(const ::server_client::RandomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_client::RandomResponse> should match
// service_traits::MD5Sum< ::server_client::Random >
template<>
struct MD5Sum< ::server_client::RandomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_client::Random >::value();
  }
  static const char* value(const ::server_client::RandomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client::RandomResponse> should match
// service_traits::DataType< ::server_client::Random >
template<>
struct DataType< ::server_client::RandomResponse>
{
  static const char* value()
  {
    return DataType< ::server_client::Random >::value();
  }
  static const char* value(const ::server_client::RandomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_CLIENT_MESSAGE_RANDOM_H
